const fs = require('fs');

const path = 'src/data/initialData.ts';
let code = fs.readFileSync(path, 'utf8');

const startIndex = code.indexOf('export const INITIAL_TEACHERS: Teacher[] = [');
const endIndex = code.indexOf('];', startIndex) + 2;

const newTeachersArray = `export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: 'tech-math-1',
    name: 'أ. مروة كمال الساعدي',
    subject: 'الرياضيات',
    email: 'marwa.alsaadi@maysan-gifted.edu.iq',
    phone: '07701112233',
    assignedGrades: ['الصف السادس العلمي', 'الصف الخامس العلمي'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2020-09-01',
    gender: 'female',
    rating: 4.8,
    availableDays: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
  },
  {
    id: 'tech-math-2',
    name: 'أ. زينب حسن الجابري',
    subject: 'الرياضيات',
    email: 'zainab.aljabiri@maysan-gifted.edu.iq',
    phone: '07702223344',
    assignedGrades: ['الصف الرابع العلمي', 'الصف الثالث المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2021-09-01',
    gender: 'female',
    rating: 4.5,
    availableDays: ['الأحد', 'الإثنين', 'الأربعاء'],
  },
  {
    id: 'tech-math-3',
    name: 'أ. فاطمة علي الحسني',
    subject: 'الرياضيات',
    email: 'fatima.alhasani@maysan-gifted.edu.iq',
    phone: '07703334455',
    assignedGrades: ['الصف الثاني المتوسط', 'الصف الأول المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2022-09-01',
    gender: 'female',
    rating: 4.9,
    availableDays: ['الإثنين', 'الثلاثاء', 'الخميس'],
  },
  {
    id: 'tech-phys-1',
    name: 'أ. نور عبد الكريم النعيمي',
    subject: 'الفيزياء',
    email: 'noor.alnuaimi@maysan-gifted.edu.iq',
    phone: '07704445566',
    assignedGrades: ['الصف السادس العلمي', 'الصف الخامس العلمي'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2019-09-01',
    gender: 'female',
    rating: 4.7,
    availableDays: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
  },
  {
    id: 'tech-phys-2',
    name: 'أ. هدى فاضل الموسوي',
    subject: 'الفيزياء',
    email: 'huda.almosawi@maysan-gifted.edu.iq',
    phone: '07705556677',
    assignedGrades: ['الصف الرابع العلمي', 'الصف الثالث المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2021-09-01',
    gender: 'female',
    rating: 4.6,
    availableDays: ['الأحد', 'الثلاثاء', 'الخميس'],
  },
  {
    id: 'tech-phys-3',
    name: 'أ. زهراء كاظم الشمري',
    subject: 'الفيزياء',
    email: 'zahraa.alshammari@maysan-gifted.edu.iq',
    phone: '07706667788',
    assignedGrades: ['الصف الثاني المتوسط', 'الصف الأول المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2023-09-01',
    gender: 'female',
    rating: 4.9,
    availableDays: ['الإثنين', 'الأربعاء', 'الخميس'],
  },
  {
    id: 'tech-chem-1',
    name: 'أ. ريم صلاح التميمي',
    subject: 'الكيمياء',
    email: 'reem.altamimi@maysan-gifted.edu.iq',
    phone: '07707778899',
    assignedGrades: ['الصف السادس العلمي', 'الصف الخامس العلمي'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2020-09-01',
    gender: 'female',
    rating: 4.8,
    availableDays: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
  },
  {
    id: 'tech-chem-2',
    name: 'أ. سارة ماجد العبيدي',
    subject: 'الكيمياء',
    email: 'sara.alobaidi@maysan-gifted.edu.iq',
    phone: '07708889900',
    assignedGrades: ['الصف الرابع العلمي', 'الصف الثالث المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'إجازة أمومة',
    joinedDate: '2019-09-01',
    gender: 'female',
    rating: 4.7,
    availableDays: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
  },
  {
    id: 'tech-chem-3',
    name: 'أ. إيمان طارق العزاوي',
    subject: 'الكيمياء',
    email: 'eman.alazzawi@maysan-gifted.edu.iq',
    phone: '07709990011',
    assignedGrades: ['الصف الثاني المتوسط', 'الصف الأول المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2022-09-01',
    gender: 'female',
    rating: 4.5,
    availableDays: ['الأحد', 'الثلاثاء', 'الأربعاء'],
  },
  {
    id: 'tech-bio-1',
    name: 'أ. داليا سعد الخفاجي',
    subject: 'الأحياء',
    email: 'dalia.alkhafaji@maysan-gifted.edu.iq',
    phone: '07710001122',
    assignedGrades: ['الصف السادس العلمي', 'الصف الخامس العلمي'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2020-09-01',
    gender: 'female',
    rating: 4.9,
    availableDays: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
  },
  {
    id: 'tech-bio-2',
    name: 'أ. ليلى جاسم الربيعي',
    subject: 'الأحياء',
    email: 'laila.alrubaye@maysan-gifted.edu.iq',
    phone: '07711112233',
    assignedGrades: ['الصف الرابع العلمي', 'الصف الثالث المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2021-09-01',
    gender: 'female',
    rating: 4.6,
    availableDays: ['الإثنين', 'الثلاثاء', 'الخميس'],
  },
  {
    id: 'tech-bio-3',
    name: 'أ. خديجة حميد الكناني',
    subject: 'الأحياء',
    email: 'khadija.alkinani@maysan-gifted.edu.iq',
    phone: '07712223344',
    assignedGrades: ['الصف الثاني المتوسط', 'الصف الأول المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2023-09-01',
    gender: 'female',
    rating: 4.7,
    availableDays: ['الأحد', 'الأربعاء', 'الخميس'],
  },
  {
    id: 'tech-arab-1',
    name: 'أ. سهى عبد الرضا الاسدي',
    subject: 'اللغة العربية',
    email: 'suha.alasadi@maysan-gifted.edu.iq',
    phone: '07713334455',
    assignedGrades: ['الصف السادس العلمي', 'الصف الخامس العلمي', 'الصف الرابع العلمي'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2019-09-01',
    gender: 'female',
    rating: 4.8,
    availableDays: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
  },
  {
    id: 'tech-arab-2',
    name: 'أ. مروة شاكر العبودي',
    subject: 'اللغة العربية',
    email: 'marwa.alaboudi@maysan-gifted.edu.iq',
    phone: '07714445566',
    assignedGrades: ['الصف الثالث المتوسط', 'الصف الثاني المتوسط', 'الصف الأول المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2020-09-01',
    gender: 'female',
    rating: 4.6,
    availableDays: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
  },
  {
    id: 'tech-eng-1',
    name: 'أ. بان علي الدراجي',
    subject: 'اللغة الإنكليزية',
    email: 'ban.aldarraji@maysan-gifted.edu.iq',
    phone: '07715556677',
    assignedGrades: ['الصف السادس العلمي', 'الصف الخامس العلمي', 'الصف الرابع العلمي'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2021-09-01',
    gender: 'female',
    rating: 4.9,
    availableDays: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
  },
  {
    id: 'tech-eng-2',
    name: 'أ. هبة طارق البياتي',
    subject: 'اللغة الإنكليزية',
    email: 'hiba.albayati@maysan-gifted.edu.iq',
    phone: '07716667788',
    assignedGrades: ['الصف الثالث المتوسط', 'الصف الثاني المتوسط', 'الصف الأول المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2022-09-01',
    gender: 'female',
    rating: 4.7,
    availableDays: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
  },
  {
    id: 'tech-cs-mohammed',
    name: 'محمد نعمة كاظم كريدي الوحيلي',
    subject: 'الحاسوب',
    email: 'mohammed.alwuhaili@maysan-gifted.edu.iq',
    phone: '07705555701',
    assignedGrades: ['الصف الأول المتوسط', 'الصف الثاني المتوسط', 'الصف الرابع العلمي', 'الصف الخامس العلمي'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2019-09-01',
    gender: 'male',
    rating: 5.0,
    availableDays: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
  },
  {
    id: 'tech-cs-1',
    name: 'أ. مريم عماد الكعبي',
    subject: 'الحاسوب',
    email: 'maryam.alkaabi@maysan-gifted.edu.iq',
    phone: '07717778899',
    assignedGrades: ['الصف السادس العلمي', 'الصف الثالث المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2020-09-01',
    gender: 'female',
    rating: 4.8,
    availableDays: ['الإثنين', 'الثلاثاء', 'الأربعاء'],
  },
  {
    id: 'tech-cs-2',
    name: 'أ. شهد قاسم الجنابي',
    subject: 'الحاسوب',
    email: 'shahad.aljanabi@maysan-gifted.edu.iq',
    phone: '07718889900',
    assignedGrades: ['الصف الثاني المتوسط', 'الصف الأول المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2023-09-01',
    gender: 'female',
    rating: 4.5,
    availableDays: ['الأحد', 'الخميس'],
  },
  {
    id: 'tech-islamic-1',
    name: 'أ. ساجدة جبار المياحي',
    subject: 'التربية الإسلامية',
    email: 'sajida.almayahi@maysan-gifted.edu.iq',
    phone: '07719990011',
    assignedGrades: ['الصف السادس العلمي', 'الصف الخامس العلمي', 'الصف الرابع العلمي'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2019-09-01',
    gender: 'female',
    rating: 4.9,
    availableDays: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
  },
  {
    id: 'tech-islamic-2',
    name: 'أ. أنعام ناصر الشويلي',
    subject: 'التربية الإسلامية',
    email: 'anaam.alshuwaili@maysan-gifted.edu.iq',
    phone: '07720001122',
    assignedGrades: ['الصف الثالث المتوسط', 'الصف الثاني المتوسط', 'الصف الأول المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2021-09-01',
    gender: 'female',
    rating: 4.7,
    availableDays: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
  },
  {
    id: 'tech-soc-1',
    name: 'أ. بشرى صادق الكعبي',
    subject: 'الاجتماعيات',
    email: 'bushra.alkaabi@maysan-gifted.edu.iq',
    phone: '07721112233',
    assignedGrades: ['الصف الثالث المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2020-09-01',
    gender: 'female',
    rating: 4.8,
    availableDays: ['الإثنين', 'الأربعاء', 'الخميس'],
  },
  {
    id: 'tech-soc-2',
    name: 'أ. سميرة حسين الشمري',
    subject: 'الاجتماعيات',
    email: 'samira.alshammari@maysan-gifted.edu.iq',
    phone: '07722223344',
    assignedGrades: ['الصف الثاني المتوسط', 'الصف الأول المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2022-09-01',
    gender: 'female',
    rating: 4.6,
    availableDays: ['الأحد', 'الثلاثاء', 'الخميس'],
  },
  {
    id: 'tech-fr-1',
    name: 'أ. ريم غسان اليعقوبي',
    subject: 'اللغة الفرنسية',
    email: 'reem.alyaqoubi@maysan-gifted.edu.iq',
    phone: '07723334455',
    assignedGrades: ['الصف السادس العلمي', 'الصف الخامس العلمي', 'الصف الرابع العلمي', 'الصف الثالث المتوسط', 'الصف الثاني المتوسط', 'الصف الأول المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2023-09-01',
    gender: 'female',
    rating: 4.9,
    availableDays: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
  },
  {
    id: 'tech-kurd-1',
    name: 'أ. ليلان محمود الزيباري',
    subject: 'اللغة الكردية',
    email: 'leelan.alzibari@maysan-gifted.edu.iq',
    phone: '07724445566',
    assignedGrades: ['الصف الرابع العلمي'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2021-09-01',
    gender: 'female',
    rating: 4.7,
    availableDays: ['الأحد', 'الإثنين', 'الثلاثاء'],
  },
  {
    id: 'tech-moral-1',
    name: 'أ. هند عباس الموسوي',
    subject: 'التربية الأخلاقية',
    email: 'hind.almosawi@maysan-gifted.edu.iq',
    phone: '07725556677',
    assignedGrades: ['الصف الأول المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2024-09-01',
    gender: 'female',
    rating: 5.0,
    availableDays: ['الثلاثاء', 'الأربعاء'],
  },
  {
    id: 'tech-art-1',
    name: 'أ. سحر حامد الخفاجي',
    subject: 'التربية الفنية',
    email: 'sahar.alkhafaji@maysan-gifted.edu.iq',
    phone: '07726667788',
    assignedGrades: ['الصف الثالث المتوسط', 'الصف الثاني المتوسط', 'الصف الأول المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2020-09-01',
    gender: 'female',
    rating: 4.8,
    availableDays: ['الإثنين', 'الأربعاء', 'الخميس'],
  },
  {
    id: 'tech-pe-1',
    name: 'أ. ميادة سالم السوداني',
    subject: 'التربية الرياضية',
    email: 'mayada.alsudani@maysan-gifted.edu.iq',
    phone: '07727778899',
    assignedGrades: ['الصف الثالث المتوسط', 'الصف الثاني المتوسط', 'الصف الأول المتوسط'],
    assignedSections: ['أ', 'ب'],
    status: 'نشط',
    joinedDate: '2019-09-01',
    gender: 'female',
    rating: 4.9,
    availableDays: ['الأحد', 'الثلاثاء', 'الخميس'],
  }
];`;

code = code.substring(0, startIndex) + newTeachersArray + code.substring(endIndex);

fs.writeFileSync(path, code);
console.log('Updated INITIAL_TEACHERS');
